#!/usr/bin/env python3
"""Generate both app and shared-module strings from the reviewed five-language text list."""
import json
from pathlib import Path

root = Path(__file__).resolve().parent.parent
catalog = json.loads((root / 'docs/ui/localization.json').read_text())
languages = ['en', 'ja', 'es', 'fr']
for key, values in catalog.items():
    if len(values) != len(languages) or any(not value for value in values):
        raise ValueError(f'Incomplete translation: {key}')
for language in ['zh-Hans'] + languages:
    lines = ['/* Generated by Scripts/generate-localizations.py. */']
    for key, values in sorted(catalog.items()):
        value = key if language == 'zh-Hans' else values[languages.index(language)]
        if key.count('%@') != value.count('%@'):
            raise ValueError(f'Placeholder mismatch: {key} ({language})')
        lines.append(f'{json.dumps(key, ensure_ascii=False)} = {json.dumps(value, ensure_ascii=False)};')
    for folder in ['Apps/Clickport/Resources', 'Packages/ClickportCore/Sources/ClickportCore/Resources']:
        path = root / folder / f'{language}.lproj/Localizable.strings'
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text('\n'.join(lines) + '\n')
print(f'Generated {len(catalog)} entries in five languages.')

# Inventory still-untranslated source text. Interpolations are retained for manual review.
import re
pending = {}
for folder in ['Apps/Clickport', 'Extensions/FinderExtension', 'Packages/ClickportCore/Sources/ClickportCore']:
    for source in (root / folder).rglob('*.swift'):
        for number, line in enumerate(source.read_text().splitlines(), 1):
            for match in re.finditer(r'"((?:\\.|[^"\\])*)"', line):
                key = match.group(1).replace(r"\n", "\n")
                if re.search(r'[\u4e00-\u9fff]', key) and key not in catalog:
                    pending.setdefault(key, f'{source.relative_to(root)}:{number}')
report = ['# 待翻译文案', '', '由脚本从 Swift 字符串生成，包含动态插值；用于逐项补齐，不代表运行时覆盖率检查。', '', '| 文案 | 首次出现 |', '| --- | --- |']
for key, location in sorted(pending.items()):
    report.append(f'| {key.replace("|", "&#124;")} | `{location}` |')
(root / 'docs/ui/localization-pending.md').write_text('\n'.join(report) + '\n')
print(f'{len(pending)} source strings remain for review.')
